version: "3"

services:
  identity:
          container_name: apiexchangerate
          restart: always
          build: .
          ports:
              - "4002:4000"
          links:
            - mongo
  mongo:
          container_name: mongodbxr
          image: mongo
          ports: 
              - "27019:27019"
